{% set version = '2.0.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-apatables
  version: {{ version|replace("-", "_") }}

source:
  fn: apaTables_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/apaTables_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/apaTables/apaTables_{{ version }}.tar.gz
  sha256: 6a3f4ed67f4d7794cb74b81c9c7faad4e473661c8328f7c668ae18dab0342841

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-boot
    - r-broom
    - r-car
    - r-dplyr
    - r-tibble
  run:
    - r-base
    - r-boot
    - r-broom
    - r-car
    - r-dplyr
    - r-tibble

test:
  commands:
    - $R -e "library('apaTables')"           # [not win]
    - "\"%R%\" -e \"library('apaTables')\""  # [win]

about:
  home: https://github.com/dstanley4/apaTables
  license: MIT
  summary: A common task faced by researchers is the creation of APA style (i.e., American Psychological
    Association style) tables from statistical output. In R a large number of function
    calls are often needed to obtain all of the desired information for a single APA
    style table. As well, the process of manually creating APA style tables in a word
    processor is prone to transcription errors. This package creates Word files (.doc
    files) containing APA style tables for several types of analyses. Using this package
    minimizes transcription errors and reduces the number commands needed by the user.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
