# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "W5ECAjYkMGUGyizfmsO48WAKzvz0v01jc55SDTQk3QqWl/O04yq6ZlHaJ7MIJ5MoDhbDZWJHBYPyW2McCU/gipmWIeQrhef4PqA8CO+woTJhMZmVX6pwZYILqRLNN1r/Zzy9r5tdpr4PUwXrHYRqL9DTXOZgXMc3k4sSskWFedQ4HdNqa3rDVTpx8Ivqf9r7ddt6sg7HtbIOgWJ193pQ0yqZWR2rzd34l4nfKvEO2Vp8zVMm9RkeTy5UBaYwZmINYJd0gDkcSHYRBccAo2b3X5yiXC25bF+4qBxQ0mEkUcpJ/R9nvzIAFEhzLxNXw6ott/EATUYRK1ANv3zgpDYXbcvb+/vWnq6go7L+w4Ug4r1hfU4Bt98PAM76KDzQDA8Mm3mxWd+KlEn+OIjF/NZ19iPy1NmgD1HD+ofBMy/ZD0eT7blOM8mf20qUJUEuEUAyhm2rSClA6+f5xzJkjCvx3o/uV7DHd0wNo42HS1C84cAM8fzNq0yxG9tvLAWUUCYwntMvVCOrUF4ZBAMKbar0rBrT65KmPoM1FEf1R4oajNjur2kOhorAIRwFZnJpkfjc4zuEIJM8QirNeikZZxtgnkDD4xWLr9IlEALtCn1ZiN34kUPVf7uhz+tXAMNUqOScZiawXOhR88J8ryP8cglGx5aZqTCvjiCChcsZJrdm+qE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
