travis:
  secure:
    BINSTAR_TOKEN: Q5bJ8gGe2kAHGLMmI3pmI7PthLVnXvhsmJ6bT649tJBFhmkUWynNEvm10qFSj4nwWgi96qu51Zv5qA+Ubm3fv9JneQfqiWTJB+wvwTQT1rw7IiMyCTCILs0gZd+OtnyP6JrDJ8Iem9rBYgJC428h1f8hMpy3bRGvk8dHCMxZpsaYtM/5+YUC4KNbzV4HvLueHgcN0sXtHkZhsDemc0eL18uNmaPgBBxicA9RPzb3jJ96RvC2PLbj9MCzN2RjebfwNlf/xN6UqGPxiKMjhqImQvuY781TdCitoP1yEUc0kPT0OXZ26EhN2vKfJKLnDhTfHY5CpEQ0YY+uUwt1QMQEstroGMri3GJZb+IZ5OLP7eaK892z8uo58gvQKQ+FgKzqcURIxn+MWWfsPeBVSRwYQlvIeSnyJ8TyPBPShdUif23Ep3TRqQQ9QTZOeDK63EUTTQ0XMpxnqKQDCMxQAB14/t1c1lFkM44D5VppKw9+WN3oADCF9aoe5IZmrvTuf/GIJFULd4nc+DhegvZzjNqxdKI7ZoRCO+WE+CrG2hUodSVemazQkf3//xZg+KISgcFDqLKexAYEfZ6fn8KqItjjHJhObsxsippcxVZjfximjCaKeTirPbelkUmykVBQ7s0b4if0YtBfg2css93YdD0rfVgc34RjDd0ut4RRJz0a6JQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
