appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: W5ECAjYkMGUGyizfmsO48WAKzvz0v01jc55SDTQk3QqWl/O04yq6ZlHaJ7MIJ5MoDhbDZWJHBYPyW2McCU/gipmWIeQrhef4PqA8CO+woTJhMZmVX6pwZYILqRLNN1r/Zzy9r5tdpr4PUwXrHYRqL9DTXOZgXMc3k4sSskWFedQ4HdNqa3rDVTpx8Ivqf9r7ddt6sg7HtbIOgWJ193pQ0yqZWR2rzd34l4nfKvEO2Vp8zVMm9RkeTy5UBaYwZmINYJd0gDkcSHYRBccAo2b3X5yiXC25bF+4qBxQ0mEkUcpJ/R9nvzIAFEhzLxNXw6ott/EATUYRK1ANv3zgpDYXbcvb+/vWnq6go7L+w4Ug4r1hfU4Bt98PAM76KDzQDA8Mm3mxWd+KlEn+OIjF/NZ19iPy1NmgD1HD+ofBMy/ZD0eT7blOM8mf20qUJUEuEUAyhm2rSClA6+f5xzJkjCvx3o/uV7DHd0wNo42HS1C84cAM8fzNq0yxG9tvLAWUUCYwntMvVCOrUF4ZBAMKbar0rBrT65KmPoM1FEf1R4oajNjur2kOhorAIRwFZnJpkfjc4zuEIJM8QirNeikZZxtgnkDD4xWLr9IlEALtCn1ZiN34kUPVf7uhz+tXAMNUqOScZiawXOhR88J8ryP8cglGx5aZqTCvjiCChcsZJrdm+qE=
conda_forge_output_validation: true
